# Generated by Django 3.1.1 on 2020-09-06 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Course memrise ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Course name')),
                ('url', models.CharField(max_length=1024, verbose_name="Course's URL")),
                ('difficult', models.IntegerField(verbose_name='Number of difficult words in the course')),
                ('num_words', models.IntegerField(verbose_name='Number of words in the course')),
                ('num_levels', models.IntegerField(verbose_name='Number of levels in the course')),
                ('difficult_url', models.CharField(max_length=1024, verbose_name="Difficult's URL")),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Number of level')),
                ('name', models.CharField(max_length=1024, verbose_name='Level name')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memrise.course')),
            ],
            options={
                'unique_together': {('number', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name="Memrise's word ID")),
                ('word_a', models.CharField(max_length=1024, verbose_name='Original word')),
                ('word_b', models.CharField(max_length=1024, null=True, verbose_name='Translate')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memrise.level')),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='URL')),
                ('course_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_url', to='memrise.course')),
            ],
        ),
    ]
