# Generated by Django 3.1.1 on 2020-09-11 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memrise', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='level',
            unique_together=set(),
        ),
    ]
