# Generated by Django 3.1.2 on 2020-10-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memrise', '0002_auto_20201015_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_disable',
            field=models.BooleanField(default=False, verbose_name='Course disable'),
        ),
    ]
